In [1]:
import torch

In [2]:
a = [[11,12,13],[21,22,23],[31,32,33]]
a = torch.tensor(a)
a

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])

In [5]:
# Number of dimensions
a.ndimension()

2

In [6]:
# Shape
a.shape

torch.Size([3, 3])

In [9]:
# Number of elements
a.size()

torch.Size([3, 3])

In [12]:
# Accessing elements by index
print(a[0][0])
print(a[0,0])
print(a[0,0:2])

tensor(11)
tensor(11)
tensor([11, 12])


## Basic Operations

In [14]:
# Summing two 2D tensors
a = torch.tensor([[1,0],[0,1]])
b = torch.tensor([[2,1],[1,2]])
print(a)
print(b)
a+b

tensor([[1, 0],
        [0, 1]])
tensor([[2, 1],
        [1, 2]])


tensor([[3, 1],
        [1, 3]])

In [15]:
# Multiplication by a scalar
c = 2*a
c

tensor([[2, 0],
        [0, 2]])

In [16]:
# Product between two tensors
c = a*b
c

tensor([[2, 0],
        [0, 2]])

In [24]:
# Dot Product
a = torch.tensor([[0,1,1],[1,0,1]])
b = torch.tensor([[1],[1],[-1]])
print(a)
print(b)
c = torch.mm(a,b)
c

tensor([[0, 1, 1],
        [1, 0, 1]])
tensor([[ 1],
        [ 1],
        [-1]])


tensor([[0],
        [0]])