## Creating Dataset

In [2]:
import torch
from torch.utils.data import Dataset

class toy_set(Dataset):
    def __init__(self, length=100, transform=None):
        self.x = 2*torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.len = length
        self.transform = transform

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample

    def __len__(self):
        return self.len

In [8]:
dataset = toy_set()
print(len(dataset))

100


In [9]:
print(dataset[0])

(tensor([2., 2.]), tensor([1.]))


## Transform

In [13]:
# Using Transform
class add_mult(object):
    def __init__(self, addx=1, muly=1):
        self.addx = addx
        self.muly = muly

    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y * self.muly
        sample = x, y
        return sample
    
#testing class
am = add_mult()
sample = dataset[0]
print(am(sample))

(tensor([3., 3.]), tensor([1.]))


In [14]:
#Adding class to transform
dataset = toy_set(transform=am)
print(len(dataset))
print(dataset[0])

100
(tensor([3., 3.]), tensor([1.]))


## Transform Compose

This form applies multiple transforms in the data. It follows the pipeline:

<img src="images/transforms.svg" width="50%"/>

Where `add_mult()` is the class that add `X` values and multiply `y` values. Next, the class `mult()` multiplies data by `100`. The `mul` class is defined as:

In [15]:
# Using multiple transforms at the same time
class mult(object):
    def __init__(self, mul=100):
        self.mul = mul

    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x * self.mul
        y = y * self.mul
        sample = x, y
        return sample
    
#testing mult
ml = mult()
sample_ = ml(dataset[0])
print(sample_)

(tensor([300., 300.]), tensor([100.]))


In [17]:
# using multiple transformations
from torchvision import transforms

data_transforms = transforms.Compose([add_mult(), mult()])

# create the dataset using transforms
dataset_tr = toy_set(transform=data_transforms)
print(len(dataset_tr))
print(dataset_tr[0])

100
(tensor([300., 300.]), tensor([100.]))
