In [8]:
A = [1 2 3; 10 20 30; 100 200 300];
B = [7 8 9; 70 80 90; 170 180 190];

% multiply two matrices
A*B

ans =

     657     708     759
    6570    7080    7590
   65700   70800   75900



In [6]:
% multiplication elementwise
A.*B 

% also applies to:
% - division: 
%% A./B
% - log scale:
%% log(A)
% - exponential:
%% exp(A)
% - absolute value
%% abs(A)

ans =

       7      16      27
     700    1600    2700
   17000   36000   57000



In [10]:
% - Adding 1 to each element
A = A + ones(length(A), 1)
% or just add 1 to matrix
A + 1

A =

     3     4     5
    12    22    32
   102   202   302

ans =

     4     5     6
    13    23    33
   103   203   303



In [11]:
% transposed of a matrix
A'

ans =

     3    12   102
     4    22   202
     5    32   302



In [24]:
A
% maximum value of each column
max(A)

% maximum value and its index
[maxi, index] = max(A)

%columnwise maximum
max(A,[],1) %max dimension in dimension 1 of A - columns
max(A,[],2) %max dimension in dimension 2 of A - rows

%maximum value of the whole matrix
max(max(A))

A =

     3     4     5
    12    22    32
   102   202   302

ans =

   102   202   302

maxi =

   102   202   302

index =

   3   3   3

ans =

   102   202   302

ans =

     5
    32
   302

ans =  302


In [16]:
% elementwise comparison
R = [1 2 3 4];

R < 3 % 1 True 0 False

ans =

   1   1   0   0



In [17]:
% finding elements
find(R < 3)

ans =

   1   2



In [19]:
% create a magic square with size=N
m = magic(3)

m =

   8   1   6
   3   5   7
   4   9   2



In [20]:
% return the index of the row and column where the elements found are
[r, c] = find(m < 7)

r =

   2
   3
   1
   2
   1
   3

c =

   1
   1
   2
   2
   3
   3



In [21]:
% sum all the elements
sum(R)
% product of all elements
prod(R)

ans =  10
ans =  24


In [25]:
% round elements down
floor(R)
% round elements up
ceil(R)

ans =

   1   2   3   4

ans =

   1   2   3   4



In [26]:
A
%flip the matrix by the top
flipud(A)

A =

     3     4     5
    12    22    32
   102   202   302

ans =

   102   202   302
    12    22    32
     3     4     5



In [27]:
% invert the matrix
pinv(A)

ans =

   0.3733734   0.3355856  -0.0422923
   0.0925926   0.0833333  -0.0092593
  -0.1881882  -0.1689189   0.0237738

