## Question 1:

In [31]:
A = [1 2; 3 4; 5 6]
B = [1 2 3; 4 5 6]

A =

   1   2
   3   4
   5   6

B =

   1   2   3
   4   5   6



In [32]:
C = A' + B

C =

    2    5    8
    6    9   12



In [33]:
C = B * A

C =

   22   28
   49   64



In [34]:
C = B' * A

error: operator *: nonconformant arguments (op1 is 3x2, op2 is 3x2)


## Question 2:

In [5]:
A = magic(4)

A =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1



In [6]:
B = A(1:4,1:2)

B =

   16    2
    5   11
    9    7
    4   14



In [7]:
B = A(:,1:2)

B =

   16    2
    5   11
    9    7
    4   14



## Question 3:

Let A be a 10x10 matrix and x be a 10-element vector. Your friend wants to compute the product Ax and writes the following code:

In [9]:
A = magic(3)
x = [1;2;3]
v = zeros(3, 1);

for i = 1:3
  for j = 1:3
    v(i) = v(i) + A(i, j) * x(j);
  end
end

A =

   8   1   6
   3   5   7
   4   9   2

x =

   1
   2
   3



In [10]:
v

v =

   28
   34
   28



In [11]:
V = A * x

V =

   28
   34
   28



## Question 4:

Say you have two column vectors v and w, each with 7 elements (i.e., they have dimensions 7x1). Consider the following code:

```octave
z = 0;
for i = 1:7
  z = z + v(i) * w(i)
end
```

Which of the following vectorizations correctly compute z? Check all that apply.

In [35]:
v = [1;2;3]
w = [10;20;30]

z = 0;
for i = 1:3
  z = z + v(i) * w(i)
end
disp(z)

v =

   1
   2
   3

w =

   10
   20
   30

z =  10
z =  50
z =  140
 140


In [19]:
z = sum (v .* w)

z =  140


In [36]:
z = w' * v

z =  140


In [38]:
z = w * v'

z =

   10   20   30
   20   40   60
   30   60   90



## Question 5

In Octave/Matlab, many functions work on single numbers, vectors, and matrices. For example, the sin function when applied to a matrix will return a new matrix with the sin of each element. But you have to be careful, as certain functions have different behavior. Suppose you have an 7x7 matrix X. You want to compute the log of every element, the square of every element, add 1 to every element, and divide every element by 4. You will store the results in four matrices, A,B,C,D. One way to do so is the following code:

```octave
for i = 1:7
  for j = 1:7
    A(i, j) = log(X(i, j));
    B(i, j) = X(i, j) ^ 2;
    C(i, j) = X(i, j) + 1;
    D(i, j) = X(i, j) / 4;
  end
end
```

Which of the following correctly compute A,B,C, or D? Check all that apply.

In [21]:
X = [1 2 3; 4 5 6; 7 8 9]
A = zeros(3);
B = zeros(3);
C = zeros(3);
D = zeros(3);

for i = 1:3
  for j = 1:3
    A(i, j) = log(X(i, j));
    B(i, j) = X(i, j) ^ 2;
    C(i, j) = X(i, j) + 1;
    D(i, j) = X(i, j) / 4;
  end
end

X =

   1   2   3
   4   5   6
   7   8   9



In [22]:
A % log

A =

   0.00000   0.69315   1.09861
   1.38629   1.60944   1.79176
   1.94591   2.07944   2.19722



In [23]:
B % ^2

B =

    1    4    9
   16   25   36
   49   64   81



In [24]:
C % +1

C =

    2    3    4
    5    6    7
    8    9   10



In [25]:
D % /4

D =

   0.25000   0.50000   0.75000
   1.00000   1.25000   1.50000
   1.75000   2.00000   2.25000



In [26]:
X = [1 2 3; 4 5 6; 7 8 9]
A = zeros(3);
B = zeros(3);
C = zeros(3);
D = zeros(3);

X =

   1   2   3
   4   5   6
   7   8   9



In [27]:
A = log (X)

A =

   0.00000   0.69315   1.09861
   1.38629   1.60944   1.79176
   1.94591   2.07944   2.19722



In [39]:
B = X .^ 2

B =

    1    4    9
   16   25   36
   49   64   81



In [29]:
C = X + 1

C =

    2    3    4
    5    6    7
    8    9   10



In [30]:
D = X / 4

D =

   0.25000   0.50000   0.75000
   1.00000   1.25000   1.50000
   1.75000   2.00000   2.25000

