In [ ]:
%% Add to a file costFunction.m
function J = costFunctionJ(X, y, theta)

% X is the "design matrix" containing our training examples.
% y is the class labels

m = size(X, 1);         % number of training examples
predictions = X*theta;  % predictions of hypothesis on all m examples
sqrErrors = (predictions-y).^2; %squared errors

J = 1/(2*m) * sum(sqrErrors);

In [2]:
X = [1 1; 1 2; 1 3]
y = [1; 2; 3]
theta = [0;0]

m = size(X, 1);         % number of training examples
predictions = X*theta;  % predictions of hypothesis on all m examples
sqrErrors = (predictions-y).^2; %squared errors

J = 1/(2*m) * sum(sqrErrors)

X =

   1   1
   1   2
   1   3

y =

   1
   2
   3

theta =

   0
   0

J =  2.3333


In [3]:
v = zeros(10, 1);
A = magic(10)
x = [1:10]
for i = 1:10
  for j = 1:10
    v(i) = v(i) + A(i, j) * x(j);
  end
end
disp(v)

A =

    92    99     1     8    15    67    74    51    58    40
    98    80     7    14    16    73    55    57    64    41
     4    81    88    20    22    54    56    63    70    47
    85    87    19    21     3    60    62    69    71    28
    86    93    25     2     9    61    68    75    52    34
    17    24    76    83    90    42    49    26    33    65
    23     5    82    89    91    48    30    32    39    66
    79     6    13    95    97    29    31    38    45    72
    10    12    94    96    78    35    37    44    46    53
    11    18   100    77    84    36    43    50    27    59

x =

    1    2    3    4    5    6    7    8    9   10

   2650
   2680
   2940
   2680
   2650
   2825
   2855
   2815
   2855
   2825


In [4]:
A = magic(10)
x = [1;2;3;4;5;6;7;8;9;10]
v = A*x

A =

    92    99     1     8    15    67    74    51    58    40
    98    80     7    14    16    73    55    57    64    41
     4    81    88    20    22    54    56    63    70    47
    85    87    19    21     3    60    62    69    71    28
    86    93    25     2     9    61    68    75    52    34
    17    24    76    83    90    42    49    26    33    65
    23     5    82    89    91    48    30    32    39    66
    79     6    13    95    97    29    31    38    45    72
    10    12    94    96    78    35    37    44    46    53
    11    18   100    77    84    36    43    50    27    59

x =

    1
    2
    3
    4
    5
    6
    7
    8
    9
   10

v =

   2650
   2680
   2940
   2680
   2650
   2825
   2855
   2815
   2855
   2825



In [5]:
y = zeros(5,1)

y =

   0
   0
   0
   0
   0



In [14]:
X = [1 2 3; 4 5 6; 7 8 9]
A = zeros(3);
B = zeros(3);
C = zeros(3);
D = zeros(3);

for i = 1:3
  for j = 1:3
    A(i, j) = log(X(i, j));
    B(i, j) = X(i, j) ^ 2;
    C(i, j) = X(i, j) + 1;
    D(i, j) = X(i, j) / 4;
  end
end

X =

   1   2   3
   4   5   6
   7   8   9



In [15]:
A % log

A =

   0.00000   0.69315   1.09861
   1.38629   1.60944   1.79176
   1.94591   2.07944   2.19722



In [16]:
B % ^2

B =

    1    4    9
   16   25   36
   49   64   81



In [17]:
C % +1

C =

    2    3    4
    5    6    7
    8    9   10



In [18]:
D % /4

D =

   0.25000   0.50000   0.75000
   1.00000   1.25000   1.50000
   1.75000   2.00000   2.25000



In [22]:
X = [1 2 3; 4 5 6; 7 8 9]
A = zeros(3);
B = zeros(3);
C = zeros(3);
D = zeros(3);

X =

   1   2   3
   4   5   6
   7   8   9



In [21]:
A = log (X)

A =

   0.00000   0.69315   1.09861
   1.38629   1.60944   1.79176
   1.94591   2.07944   2.19722



In [24]:
B = X ^ 2

B =

    30    36    42
    66    81    96
   102   126   150



In [23]:
C = X + 1

C =

    2    3    4
    5    6    7
    8    9   10



In [20]:
D = X / 4

D =

   0.25000   0.50000   0.75000
   1.00000   1.25000   1.50000
   1.75000   2.00000   2.25000

