# Create a linearly spaced variable and a polynomial

This is a practice problem using a MATLAB script. Pressing the "Run" button will execute the code without testing if it is correct or not. Use the Run button to test your solution, see if the output is as you expect, and make sure your code is free of syntax or run time errors. 

Once you're happy with the results. Press the "Submit for Assessment" button to see how you did! The output of your code is placed below the assessment results.

1. Create a row vector x that starts at -2, ends at +2 with a step size of 0.5. 
2. Use x to create a vector y using the following equation: $y = 3x^2+2x-6$

You'll need to know how to use the colon operator and elementwise operations to complete this problem. If you're unfamilar with these terms, check out the MATLAB Onramp on the previous page as these concepts will be used frequently in the course.

In [1]:
% Create x from -2 to 2 in steps of 0.5
x = -2:0.5:2

% Use x to create y according to the formula in the description
y = 3*x.^2+2*x-6

x =

 Columns 1 through 8:

   -2.0000   -1.5000   -1.0000   -0.5000    0.0000    0.5000    1.0000    1.5000

 Column 9:

    2.0000

y =

 Columns 1 through 8:

    2.0000   -2.2500   -5.0000   -6.2500   -6.0000   -4.2500   -1.0000    3.7500

 Column 9:

   10.0000



# Calculate the area of a circle

In this problem, we'll practice writing function in the online environment. Because functions often require input variables, we can not simply run them like scripts. To test our functions, we'll use the "How to Call the Function" box. We can enter any code in this area to test your function. In most cases code will already be provided to test the function. When we press the "Run" button, the code in the "How to Call the Function" box is executed and no grading is done. Press "Submit for Assessment" to see if your function is correct!

**Task**: Write a function named areaCircle to calculate the are of a circle. 

1. The function should take one input that is the radius of the circle.
2. The function should work if the input is a scalar, vector, or matrix.
3. The function should return, one ouput, the same size as the input, that contains the area of a circle for each correspoding element.
4. If a negative radius passed as input, the function should return the value -1 to indicate the error.

In [13]:
function area = areaCircle(r)
    vec = r(:)';
    for i=1:length(vec),
        val = vec(i);
        if val < 0
            vec(i) = -1;
        else
            vec(i) = pi*val^2;
        end
    end
    area = reshape(vec, size(r));
end

function area = areaCircle_return_neg(r)
    neg = find(r<-1);
    if neg > 1
        area = -1;
    else
        area = pi*r.^2;
    end
end

r1 = 2;
r1
area1 = areaCircle(r1)

r2 = [2 5; 0.5 1];
r2
area2 = areaCircle(r2)

r3 = [1 1.5 3 -4];
r3
area3 = areaCircle(r3)

r1 =  2
area1 =  12.566
r2 =

   2.00000   5.00000
   0.50000   1.00000

area2 =

   12.56637   78.53982
    0.78540    3.14159

r3 =

   1.0000   1.5000   3.0000  -4.0000

area3 = -1
